---
- include: debian.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 8

#- include: centos.yml
#  when: ansible_disribution == 'Centos' and ansible_distribution_major_version|int >= 7
